use super::types::{
    PhysicsAllocationStats, PhysicsDebugFrame, PhysicsError, PhysicsHit, StepStats,
};
use super::validation::{is_replay_frame, validate_samples, vector3};
use super::{Collider, PhysicsDesc, RigidBody, TransformAuthority};
use crate::ecs::components::Transform;
use crate::time::FrameTime;
use glam::Vec3;
use rapier3d::prelude::{
    BroadPhaseMultiSap, CCDSolver, ColliderHandle, ColliderSet, ImpulseJointSet,
    IntegrationParameters, IslandManager, MultibodyJointSet, NarrowPhase, PhysicsPipeline,
    QueryFilter, QueryPipeline, RigidBodyHandle, RigidBodySet,
};
use std::collections::{BTreeMap, HashMap};

#[derive(Clone)]
pub(super) struct EntityPhysicsState {
    pub desc: PhysicsDesc,
    pub scale: Vec3,
    pub initial_transform: Transform,
    pub body_handle: RigidBodyHandle,
    pub collider_handles: Vec<ColliderHandle>,
}

/// Persistent Rapier state. The runtime owns no time accumulator: callers pass
/// the exact fixed-step samples generated by [`crate::time::TimeControl`].
pub struct PhysicsRuntime {
    pub(super) pipeline: PhysicsPipeline,
    pub(super) integration_parameters: IntegrationParameters,
    pub(super) islands: IslandManager,
    pub(super) broad_phase: BroadPhaseMultiSap,
    pub(super) narrow_phase: NarrowPhase,
    pub(super) bodies: RigidBodySet,
    pub(super) colliders: ColliderSet,
    pub(super) impulse_joints: ImpulseJointSet,
    pub(super) multibody_joints: MultibodyJointSet,
    pub(super) ccd_solver: CCDSolver,
    pub(super) query_pipeline: QueryPipeline,
    pub(super) entity_to_body: BTreeMap<u64, RigidBodyHandle>,
    pub(super) entity_to_colliders: BTreeMap<u64, Vec<ColliderHandle>>,
    pub(super) body_to_entity: HashMap<RigidBodyHandle, u64>,
    pub(super) collider_to_entity: HashMap<ColliderHandle, u64>,
    pub(super) entity_state: BTreeMap<u64, EntityPhysicsState>,
    pub(super) gravity: Vec3,
    pub(super) last_step_index: u64,
    pub(super) fixed_dt: Option<f32>,
    pub(super) paused: bool,
    pub(super) last_seek_frame: Option<FrameTime>,
    pub(super) allocation_stats: PhysicsAllocationStats,
    pub(super) debug_enabled: bool,
}

impl Default for PhysicsRuntime {
    fn default() -> Self {
        Self::new(Vec3::new(0.0, -9.81, 0.0))
    }
}

impl PhysicsRuntime {
    /// Creates an empty runtime with the requested world-space gravity.
    pub fn new(gravity: Vec3) -> Self {
        Self {
            pipeline: PhysicsPipeline::new(),
            integration_parameters: IntegrationParameters::default(),
            islands: IslandManager::new(),
            broad_phase: BroadPhaseMultiSap::new(),
            narrow_phase: NarrowPhase::new(),
            bodies: RigidBodySet::new(),
            colliders: ColliderSet::new(),
            impulse_joints: ImpulseJointSet::new(),
            multibody_joints: MultibodyJointSet::new(),
            ccd_solver: CCDSolver::new(),
            query_pipeline: QueryPipeline::new(),
            entity_to_body: BTreeMap::new(),
            entity_to_colliders: BTreeMap::new(),
            body_to_entity: HashMap::new(),
            collider_to_entity: HashMap::new(),
            entity_state: BTreeMap::new(),
            gravity,
            last_step_index: 0,
            fixed_dt: None,
            paused: false,
            last_seek_frame: None,
            allocation_stats: PhysicsAllocationStats::default(),
            debug_enabled: false,
        }
    }

    /// Creates one dynamic or fixed body with one Box or Sphere collider.
    /// Validation happens before Rapier is mutated, so failures leave the
    /// runtime unchanged.
    pub fn spawn_body(
        &mut self,
        entity_bits: u64,
        transform: &Transform,
        body: &RigidBody,
        collider: &Collider,
    ) -> Result<(), PhysicsError> {
        let desc = PhysicsDesc {
            body: body.clone(),
            colliders: vec![collider.clone()],
            authority: if body.is_static {
                TransformAuthority::Scene
            } else {
                TransformAuthority::Physics
            },
        };
        self.spawn_entity(entity_bits, transform, &desc)
    }

    /// Advances one Rapier step for each published time sample, in order.
    /// Invalid input is rejected before any simulation state is changed.
    pub fn step_frame(&mut self, frame_time: &FrameTime) -> Result<StepStats, PhysicsError> {
        if is_replay_frame(&frame_time.samples, self.last_step_index, self.fixed_dt) {
            return Ok(StepStats {
                active_bodies: self.bodies.len() as u32,
                ..StepStats::default()
            });
        }
        validate_samples(&frame_time.samples, self.last_step_index, self.fixed_dt)?;
        if self.paused {
            return Ok(StepStats {
                active_bodies: self.bodies.len() as u32,
                ..StepStats::default()
            });
        }
        let mut simulated_time = 0.0;
        for sample in &frame_time.samples {
            self.integration_parameters.dt = sample.dt;
            self.pipeline.step(
                &vector3(self.gravity),
                &self.integration_parameters,
                &mut self.islands,
                &mut self.broad_phase,
                &mut self.narrow_phase,
                &mut self.bodies,
                &mut self.colliders,
                &mut self.impulse_joints,
                &mut self.multibody_joints,
                &mut self.ccd_solver,
                None,
                &(),
                &(),
            );
            self.query_pipeline.update(&self.colliders);
            self.last_step_index = sample.step_index;
            self.fixed_dt = Some(sample.dt);
            simulated_time += sample.dt;
        }
        Ok(StepStats {
            substeps: frame_time.samples.len() as u32,
            simulated_time,
            active_bodies: self.bodies.len() as u32,
        })
    }

    /// Returns a body's current translation and linear velocity, if present.
    pub fn body_state(&self, entity_bits: u64) -> Option<(Vec3, Vec3)> {
        let handle = self.entity_to_body.get(&entity_bits)?;
        let body = self.bodies.get(*handle)?;
        let translation = body.translation();
        let velocity = body.linvel();
        Some((
            Vec3::new(translation.x, translation.y, translation.z),
            Vec3::new(velocity.x, velocity.y, velocity.z),
        ))
    }

    /// Returns the number of bodies currently owned by the runtime.
    pub fn body_count(&self) -> usize {
        self.entity_to_body.len()
    }

    /// Returns cumulative Rapier handle creation counts for this runtime.
    pub fn allocation_stats(&self) -> PhysicsAllocationStats {
        self.allocation_stats
    }

    /// Casts a validated world-space ray through the current collider snapshot.
    pub fn cast_ray(
        &self,
        ray: &crate::renderer::picking::Ray,
        max_toi: f32,
        filter: QueryFilter<'_>,
    ) -> Result<Option<PhysicsHit>, PhysicsError> {
        let direction_length_squared = ray.dir.length_squared();
        if !ray.origin.is_finite()
            || !ray.dir.is_finite()
            || !direction_length_squared.is_finite()
            || direction_length_squared <= f32::EPSILON
            || !max_toi.is_finite()
            || max_toi <= 0.0
        {
            return Err(PhysicsError::InvalidRay);
        }

        let ray = rapier3d::prelude::Ray::new(
            rapier3d::na::Point3::new(ray.origin.x, ray.origin.y, ray.origin.z),
            vector3(ray.dir / direction_length_squared.sqrt()),
        );
        let Some((collider_handle, intersection)) = self.query_pipeline.cast_ray_and_get_normal(
            &self.bodies,
            &self.colliders,
            &ray,
            max_toi,
            true,
            filter,
        ) else {
            return Ok(None);
        };
        let entity_bits = self
            .collider_to_entity
            .get(&collider_handle)
            .copied()
            .or_else(|| {
                self.colliders
                    .get(collider_handle)
                    .and_then(|collider| collider.parent())
                    .and_then(|body| self.body_to_entity.get(&body).copied())
            })
            .ok_or(PhysicsError::StaleHandle { entity_bits: 0 })?;
        let normal = intersection.normal;
        Ok(Some(PhysicsHit {
            entity_bits,
            toi: intersection.time_of_impact,
            normal: Vec3::new(normal.x, normal.y, normal.z),
        }))
    }

    /// Enables or disables collider wireframe extraction without changing simulation state.
    pub fn set_debug_enabled(&mut self, enabled: bool) {
        self.debug_enabled = enabled;
    }

    /// Extracts collider wireframes only when debug visualization is enabled.
    pub fn debug_frame(&self) -> Option<PhysicsDebugFrame> {
        super::debug::extract_debug_frame(self)
    }
}
