use super::types::{PhysicsError, StepStats};
use super::validation::{is_replay_frame, validate_samples, vector3};
use super::{Collider, PhysicsDesc, RigidBody, TransformAuthority};
use crate::ecs::components::Transform;
use crate::time::FrameTime;
use glam::Vec3;
use rapier3d::prelude::{
    BroadPhaseMultiSap, CCDSolver, ColliderHandle, ColliderSet, ImpulseJointSet,
    IntegrationParameters, IslandManager, MultibodyJointSet, NarrowPhase, PhysicsPipeline,
    RigidBodyHandle, RigidBodySet,
};
use std::collections::{BTreeMap, HashMap};

#[derive(Clone)]
pub(super) struct EntityPhysicsState {
    pub desc: PhysicsDesc,
    pub scale: Vec3,
    pub initial_transform: Transform,
    pub body_handle: RigidBodyHandle,
    pub collider_handles: Vec<ColliderHandle>,
}

/// Persistent Rapier state. The runtime owns no time accumulator: callers pass
/// the exact fixed-step samples generated by [`crate::time::TimeControl`].
pub struct PhysicsRuntime {
    pub(super) pipeline: PhysicsPipeline,
    pub(super) integration_parameters: IntegrationParameters,
    pub(super) islands: IslandManager,
    pub(super) broad_phase: BroadPhaseMultiSap,
    pub(super) narrow_phase: NarrowPhase,
    pub(super) bodies: RigidBodySet,
    pub(super) colliders: ColliderSet,
    pub(super) impulse_joints: ImpulseJointSet,
    pub(super) multibody_joints: MultibodyJointSet,
    pub(super) ccd_solver: CCDSolver,
    pub(super) entity_to_body: BTreeMap<u64, RigidBodyHandle>,
    pub(super) entity_to_colliders: BTreeMap<u64, Vec<ColliderHandle>>,
    pub(super) body_to_entity: HashMap<RigidBodyHandle, u64>,
    pub(super) collider_to_entity: HashMap<ColliderHandle, u64>,
    pub(super) entity_state: BTreeMap<u64, EntityPhysicsState>,
    pub(super) gravity: Vec3,
    pub(super) last_step_index: u64,
    pub(super) fixed_dt: Option<f32>,
    pub(super) paused: bool,
    pub(super) last_seek_frame: Option<FrameTime>,
}

impl Default for PhysicsRuntime {
    fn default() -> Self {
        Self::new(Vec3::new(0.0, -9.81, 0.0))
    }
}

impl PhysicsRuntime {
    /// Creates an empty runtime with the requested world-space gravity.
    pub fn new(gravity: Vec3) -> Self {
        Self {
            pipeline: PhysicsPipeline::new(),
            integration_parameters: IntegrationParameters::default(),
            islands: IslandManager::new(),
            broad_phase: BroadPhaseMultiSap::new(),
            narrow_phase: NarrowPhase::new(),
            bodies: RigidBodySet::new(),
            colliders: ColliderSet::new(),
            impulse_joints: ImpulseJointSet::new(),
            multibody_joints: MultibodyJointSet::new(),
            ccd_solver: CCDSolver::new(),
            entity_to_body: BTreeMap::new(),
            entity_to_colliders: BTreeMap::new(),
            body_to_entity: HashMap::new(),
            collider_to_entity: HashMap::new(),
            entity_state: BTreeMap::new(),
            gravity,
            last_step_index: 0,
            fixed_dt: None,
            paused: false,
            last_seek_frame: None,
        }
    }

    /// Creates one dynamic or fixed body with one Box or Sphere collider.
    /// Validation happens before Rapier is mutated, so failures leave the
    /// runtime unchanged.
    pub fn spawn_body(
        &mut self,
        entity_bits: u64,
        transform: &Transform,
        body: &RigidBody,
        collider: &Collider,
    ) -> Result<(), PhysicsError> {
        let desc = PhysicsDesc {
            body: body.clone(),
            colliders: vec![collider.clone()],
            authority: if body.is_static {
                TransformAuthority::Scene
            } else {
                TransformAuthority::Physics
            },
        };
        self.spawn_entity(entity_bits, transform, &desc)
    }

    /// Advances one Rapier step for each published time sample, in order.
    /// Invalid input is rejected before any simulation state is changed.
    pub fn step_frame(&mut self, frame_time: &FrameTime) -> Result<StepStats, PhysicsError> {
        if is_replay_frame(&frame_time.samples, self.last_step_index, self.fixed_dt) {
            return Ok(StepStats {
                active_bodies: self.bodies.len() as u32,
                ..StepStats::default()
            });
        }
        validate_samples(&frame_time.samples, self.last_step_index, self.fixed_dt)?;
        if self.paused {
            return Ok(StepStats {
                active_bodies: self.bodies.len() as u32,
                ..StepStats::default()
            });
        }
        let mut simulated_time = 0.0;
        for sample in &frame_time.samples {
            self.integration_parameters.dt = sample.dt;
            self.pipeline.step(
                &vector3(self.gravity),
                &self.integration_parameters,
                &mut self.islands,
                &mut self.broad_phase,
                &mut self.narrow_phase,
                &mut self.bodies,
                &mut self.colliders,
                &mut self.impulse_joints,
                &mut self.multibody_joints,
                &mut self.ccd_solver,
                None,
                &(),
                &(),
            );
            self.last_step_index = sample.step_index;
            self.fixed_dt = Some(sample.dt);
            simulated_time += sample.dt;
        }
        Ok(StepStats {
            substeps: frame_time.samples.len() as u32,
            simulated_time,
            active_bodies: self.bodies.len() as u32,
        })
    }

    /// Returns a body's current translation and linear velocity, if present.
    pub fn body_state(&self, entity_bits: u64) -> Option<(Vec3, Vec3)> {
        let handle = self.entity_to_body.get(&entity_bits)?;
        let body = self.bodies.get(*handle)?;
        let translation = body.translation();
        let velocity = body.linvel();
        Some((
            Vec3::new(translation.x, translation.y, translation.z),
            Vec3::new(velocity.x, velocity.y, velocity.z),
        ))
    }

    /// Returns the number of bodies currently owned by the runtime.
    pub fn body_count(&self) -> usize {
        self.entity_to_body.len()
    }
}
